Aplicación de estilos a Main.
Novanet-Studio/eduzone-fe pull request #3
Opened 2020-12-31 00:42 UTC by robertonovanet

2020-12-31 01:23 UTC, Davejs136 commented on src/assets/scss/base.scss
> +    button {
El objetivo de BEM es usar clases en vez de los elementos html, acá puedes añadir una clase para el botón del `Header`, una clase como `className="header__button"`, y en scss hacer lo siguiente:
```suggestion
    &__button { ... }
```
Y así eliminar la clase `&__login {}`, mejorando la legibilidad y evitando el nesting.

2020-12-31 02:32 UTC, Davejs136 requested changes
Buen trabajo, pero hay unos detalles que se pueden mejorar para ahorra líneas de código.

2020-12-31 02:32 UTC, Dave136 commented on src/assets/scss/base.scss
> +    button {
El objetivo de BEM es usar clases en vez de los elementos html, acá puedes añadir una clase para el botón del `Header`, una clase como `className="header__button"`, y en scss hacer lo siguiente:
```suggestion
    &__button { ... }
```
Y así eliminar la clase `&__login {}`, mejorando la legibilidad y evitando el nesting.

2020-12-31 02:32 UTC, Dave136 commented on src/assets/scss/base.scss
> +@media only screen and (min-device-width: 320px) and (-webkit-min-device-pixel-ratio: 1) and (orientation: portrait) {
Acá puedes añadir un mixin para simplificar estas lineas de código, fijate [estos mixins](https://github.com/Novanet-Studio/maximiza-fe/blob/master/src/assets/scss/_mixins.scss), y su aplicación [movil](https://github.com/Novanet-Studio/maximiza-fe/blob/master/src/assets/scss/_header.scss#L83), [tablet](https://github.com/Novanet-Studio/maximiza-fe/blob/master/src/assets/scss/_header.scss#L196)

El responsive comienza desde [aqui](https://github.com/Novanet-Studio/maximiza-fe/blob/master/src/assets/scss/_header.scss#L81)

2020-12-31 02:32 UTC, Dave136 commented on src/views/Main.scss
> +@media only screen and (min-device-width: 320px) and (-webkit-min-device-pixel-ratio: 1) and (orientation: portrait) {
En estas siguientes líneas aplica los mixins comentados anteriormente

2021-01-05 16:52 UTC, Davejs136 reviewed
Excelente bro

2021-01-05 19:07 UTC, Davejs136 reviewed
Hay varios cambios sugerido

2021-01-05 19:07 UTC, Davejs136 commented on src/App.jsx
> +    <Route path="/main">
el path de main debería ser `/`, incluyendole el prop `exac`

2021-01-05 19:07 UTC, Davejs136 commented on src/App.jsx
> +    <Route exact path="/">
remover `exact` y modidicar el path a `/login`

2021-01-06 20:12 UTC, Davejs136 reviewed
Excelente

2021-01-28 15:08 UTC, Davejs136 approved these changes
ok

2021-01-28 15:08 UTC, closed without merging